### ISSUE TITLE
does not work on Mavericks

### ISSUE THREAD

**Issue by yym2** [specialunderwear/Hosts.prefpane#24]
Not working on 10.9

**Comment by Panocha** [comment]
Spinning ball of death...

**Comment by specialunderwear** [comment]
So it is worrking for me on mavericks and yosemite. That means the issue is specific to some configuration. This will never get solved if such info is not supplied. Could be caused by virus scanners or quatantain softeware or broken permission settings or simply you cam not authenticate as an admin on the machine.

**Comment by hanachin** [comment]
Thanks for response, I tried on El Capitan 10.11.6 (15G1004), and it's works 😃
